name: Lint

on: [push, pull_request]

jobs:
  JS-Lint:
    runs-on: ubuntu-16.04
    if: startsWith( github.repository, 'elementor/' )
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: npm i
      - name: Run Lint
        run: ./node_modules/eslint/bin/eslint.js .

  PHP-Lint:
    runs-on: ubuntu-16.04
    if: startsWith( github.repository, 'elementor/' )
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@9882bed06691b3a085010c1602ce43ef18f15c5b # v2
        with:
          php-version: '7.4'
      - name: Install Dependencies
        run: |
          composer install
          composer require php-parallel-lint/php-parallel-lint
      - name: Run Lint
        run: |
          vendor/bin/phpcs -p -s -n . --standard=./phpcs.xml --extensions=php
      - name: Run PHP Syntax Lint
        run: |
          export PATH=$HOME/.composer/vendor/bin:$PATH
          php5.6 vendor/bin/parallel-lint --blame --exclude node_modules --exclude vendor .
          php7.0 vendor/bin/parallel-lint --blame --exclude node_modules --exclude vendor .
          php7.1 vendor/bin/parallel-lint --blame --exclude node_modules --exclude vendor .
          php7.2 vendor/bin/parallel-lint --blame --exclude node_modules --exclude vendor .
          php7.3 vendor/bin/parallel-lint --blame --exclude node_modules --exclude vendor .
